### ISSUE TITLE
Add different starting points

### ISSUE THREAD

**Issue by jernejs** [khoi/sorting-visualization#6]
Some sorting algorithms have problems when initial state isn't randomised - maybe add an option to have already partially sorted initial state, and one where the initial state is already sorted, but in the opposite direction.

**Comment by khoi** [comment]
@jernejs that's certainly would be nice. Thinking of a UI for that option is kinda tricky. I'm planning on adding the ability to choose:
- a reversed sorted arr
- partially sorted

**Comment by jdhrnndz** [comment]
I may have an idea for the implementation and UI for this issue. I would like to work on this one. :)

**Comment by khoi** [comment]
that'd be awesome

**Comment by jdhrnndz** [comment]
Hello. I am planning to use [Materialize](https://materializecss.com/) for the control panel

**Comment by khoi** [comment]
hey @jdhrnndz do you have a draft mockup that I could take a look at? I don't mind the use of a CSS Framework, but I'd try to keep the UI minimal

**Comment by jdhrnndz** [comment]
> hey @jdhrnndz do you have a draft mockup that I could take a look at? I don't mind the use of a CSS Framework, but I'd try to keep the UI minimal

I'll put the suggestions for UI in the following comments

**Comment by jdhrnndz** [comment]
<img width="1680" alt="Screen Shot 2019-10-16 at 10 40 53 PM" src="https://user-images.githubusercontent.com/5461644/66929801-3bac7880-f066-11e9-8fb2-00605c88e0a0.png">

This is the initial UI, with the default sorting algo.

**Comment by jdhrnndz** [comment]
<img width="1680" alt="Screen Shot 2019-10-16 at 10 40 39 PM" src="https://user-images.githubusercontent.com/5461644/66929847-4ff07580-f066-11e9-8615-cd34627030fd.png">

This is the view when selecting a different algo.

**Comment by jdhrnndz** [comment]
<img width="1680" alt="Screen Shot 2019-10-16 at 10 40 15 PM" src="https://user-images.githubusercontent.com/5461644/66929887-5da5fb00-f066-11e9-9a1e-612454ac34d1.png">

This is when the sort is started. I also have an idea on how to implement a pause/unpause feature, so take note that the label of the button has changed. The panel will be restored to full opacity when it gains focus or when the sort is done.

**Comment by khoi** [comment]
maybe instead of a modal, we could put the whole thing at the top, sort of like a navigation bar so it doesn't obstruct the main sorting UI.

Something like this would be good https://visualgo.net/bn/sorting . What do you think @jdhrnndz

**Comment by jdhrnndz** [comment]
> maybe instead of a modal, we could put the whole thing at the top, sort of like a navigation bar so it doesn't obstruct the main sorting UI.
> 
> Something like this would be good https://visualgo.net/bn/sorting . What do you think @jdhrnndz

This idea is better. I will think of the arrangement of the controls and show you once updated

**Comment by jdhrnndz** [comment]
![Sorting Algorithms Visualization UI](https://user-images.githubusercontent.com/5461644/67148615-f8efd800-f2d3-11e9-8df4-cbc01893767c.png)

Hello @khoi , What do you think of this one?

**Comment by khoi** [comment]
Looks much better. However, I actually like the idea of having the "black navigation bar" on top better. Something similar to https://visualgo.net/bn/sorting?slide=1

**Comment by jdhrnndz** [comment]
![Sorting Algorithms Visualization](https://user-images.githubusercontent.com/5461644/67158509-8a5e5900-f36b-11e9-90a6-4ba9b499c31f.png)

I added the black nav bar (not actually black - just dark)
